<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdxchko\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdxchko/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNdxchko.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNdxchko\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNdxchko\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ndxchko',
    'container.build_id' => '7c9564ca',
    'container.build_time' => 1601468710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdxchko');
